language: android

android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
  - extra
  - sys-img-armeabi-v7a-android-22

before_script:
- chmod +x gradlew

script:
- ./gradlew build check

notifications:
  email: false

